# coding=utf-8
import sqlalchemy
from sqlalchemy.orm import sessionmaker
from models import Stock, Shop, Sale, Publisher, Book, create_table

DB = 'postgresql'
LOGIN = 'postgres'
PASSWORD = 'posParol12380'
HOST = 'localhost'
PORT = '5432'
DB_NAME = 'BookShop'
DSN = f'{DB}://{LOGIN}:{PASSWORD}@{HOST}:{PORT}/{DB_NAME}'
engine = sqlalchemy.create_engine(DSN)

create_table(engine)

Session = sessionmaker(bind=engine)
session = Session()

session_list = []

publisher = input('Введите название или идентификатор издателя:  ')


def insert_data():
    shop1 = Shop(shop_name='Читай-город')
    session_list.append(shop1)
    shop2 = Shop(shop_name='Чакона')
    session_list.append(shop2)
    shop3 = Shop(shop_name='Метида')
    session_list.append(shop3)

    publisher1 = Publisher(name='Литрес')
    session_list.append(publisher1)
    publisher2 = Publisher(name='Просвещение')
    session_list.append(publisher2)
    publisher3 = Publisher(name='Эксмо')
    session_list.append(publisher3)
    publisher4 = Publisher(name='Дрофа')
    session_list.append(publisher4)
    publisher5 = Publisher(name='АСТ')
    session_list.append(publisher5)
    publisher6 = Publisher(name='Лабиринт')
    session_list.append(publisher6)
    publisher7 = Publisher(name='Питер')
    session_list.append(publisher7)
    publisher8 = Publisher(name='Алтапресс')
    session_list.append(publisher8)
    publisher9 = Publisher(name='Мир хобби')
    session_list.append(publisher9)
    publisher10 = Publisher(name='Де Агостини')
    session_list.append(publisher10)

    book1 = Book(title='Евгений Онегин', id_publisher=1)
    session_list.append(book1)
    book2 = Book(title='Капитанская дочка', id_publisher=1)
    session_list.append(book2)
    book3 = Book(title='Пиковая дама', id_publisher=1)
    session_list.append(book3)
    book4 = Book(title='Руслан и Людмила', id_publisher=1)
    session_list.append(book4)

    book5 = Book(title='Преступление и наказание', id_publisher=2)
    session_list.append(book5)
    book6 = Book(title='Идиот', id_publisher=2)
    session_list.append(book6)
    book7 = Book(title='Братья карамазовы', id_publisher=2)
    session_list.append(book7)
    book8 = Book(title='Бесы', id_publisher=2)
    session_list.append(book8)

    book9 = Book(title='Чёрный человек', id_publisher=3)
    session_list.append(book9)
    book10 = Book(title='Письмо к женщине', id_publisher=3)
    session_list.append(book10)
    book11 = Book(title='Пугачёв', id_publisher=3)
    session_list.append(book11)
    book12 = Book(title='Исповедь хулигана', id_publisher=3)
    session_list.append(book12)

    book13 = Book(title='Песнь льда и пламени', id_publisher=7)
    session_list.append(book13)
    book14 = Book(title='Битва королей', id_publisher=6)
    session_list.append(book14)
    book15 = Book(title='Буря мечей', id_publisher=5)
    session_list.append(book15)
    book16 = Book(title='Пир стервятников', id_publisher=4)
    session_list.append(book16)

    book17 = Book(title='Хоббит, или туда и обратно', id_publisher=5)
    session_list.append(book17)
    book18 = Book(title='Братство кольца', id_publisher=5)
    session_list.append(book18)
    book19 = Book(title='Две крепости', id_publisher=5)
    session_list.append(book19)
    book20 = Book(title='Властелин колец', id_publisher=5)
    session_list.append(book20)

    book21 = Book(title='Зов кукушки', id_publisher=6)
    session_list.append(book21)
    book22 = Book(title='Дурная кровь', id_publisher=6)
    session_list.append(book22)
    book23 = Book(title='Шелкопряд', id_publisher=6)
    session_list.append(book23)
    book24 = Book(title='Гарри Поттер и узник Азкабана', id_publisher=6)
    session_list.append(book24)

    book25 = Book(title='Мастер и Маргарита', id_publisher=7)
    session_list.append(book25)
    book26 = Book(title='Морфий', id_publisher=7)
    session_list.append(book26)
    book27 = Book(title='Белая гвардия', id_publisher=7)
    session_list.append(book27)
    book28 = Book(title='Собачье сердце', id_publisher=7)
    session_list.append(book28)
    # Гоголь
    book29 = Book(title='Ревизор', id_publisher=8)
    session_list.append(book29)
    book30 = Book(title='Тарас Бульба', id_publisher=8)
    session_list.append(book30)
    book31 = Book(title='Мёртвые души', id_publisher=8)
    session_list.append(book31)
    book32 = Book(title='Вий', id_publisher=8)
    session_list.append(book32)
    # Чехов
    book33 = Book(title='Палата №6', id_publisher=9)
    session_list.append(book33)
    book34 = Book(title='Человек в футляре', id_publisher=9)
    session_list.append(book34)
    book35 = Book(title='Вишнёвый сад', id_publisher=9)
    session_list.append(book35)
    book36 = Book(title='Каштанка', id_publisher=9)
    session_list.append(book36)
    # Брэдбери
    book37 = Book(title='451 градус по Фаренгейту', id_publisher=10)
    session_list.append(book37)
    book38 = Book(title='Вино из одуванчиков', id_publisher=10)
    session_list.append(book38)
    book39 = Book(title='Марсианские хроники', id_publisher=10)
    session_list.append(book39)
    book40 = Book(title='Лето, прощай', id_publisher=10)
    session_list.append(book40)

    stock1 = Stock(count=300, id_book=1, id_shop=1)
    session_list.append(stock1)
    stock2 = Stock(count=3000, id_book=2, id_shop=2)
    session_list.append(stock2)
    stock3 = Stock(count=600, id_book=3, id_shop=3)
    session_list.append(stock3)
    stock4 = Stock(count=800, id_book=4, id_shop=1)
    session_list.append(stock4)
    stock5 = Stock(count=100, id_book=5, id_shop=2)
    session_list.append(stock5)
    stock6 = Stock(count=30, id_book=6, id_shop=3)
    session_list.append(stock6)
    stock7 = Stock(count=900, id_book=7, id_shop=1)
    session_list.append(stock7)
    stock8 = Stock(count=600, id_book=8, id_shop=2)
    session_list.append(stock8)
    stock9 = Stock(count=200, id_book=9, id_shop=3)
    session_list.append(stock9)
    stock10 = Stock(count=5300, id_book=10, id_shop=1)
    session_list.append(stock10)
    stock11 = Stock(count=3900, id_book=11, id_shop=2)
    session_list.append(stock11)
    stock12 = Stock(count=90, id_book=12, id_shop=3)
    session_list.append(stock12)
    stock13 = Stock(count=700, id_book=13, id_shop=1)
    session_list.append(stock13)
    stock14 = Stock(count=60, id_book=14, id_shop=2)
    session_list.append(stock14)
    stock15 = Stock(count=300, id_book=15, id_shop=3)
    session_list.append(stock15)
    stock16 = Stock(count=850, id_book=16, id_shop=1)
    session_list.append(stock16)
    stock17 = Stock(count=369, id_book=17, id_shop=2)
    session_list.append(stock17)
    stock18 = Stock(count=378, id_book=18, id_shop=3)
    session_list.append(stock18)
    stock19 = Stock(count=987, id_book=19, id_shop=1)
    session_list.append(stock19)
    stock20 = Stock(count=354, id_book=20, id_shop=2)
    session_list.append(stock20)
    stock21 = Stock(count=987, id_book=21, id_shop=3)
    session_list.append(stock21)
    stock22 = Stock(count=123, id_book=22, id_shop=1)
    session_list.append(stock22)
    stock23 = Stock(count=159, id_book=23, id_shop=2)
    session_list.append(stock23)
    stock24 = Stock(count=357, id_book=24, id_shop=3)
    session_list.append(stock24)
    stock25 = Stock(count=852, id_book=25, id_shop=1)
    session_list.append(stock25)
    stock26 = Stock(count=654, id_book=26, id_shop=2)
    session_list.append(stock26)
    stock27 = Stock(count=789, id_book=27, id_shop=1)
    session_list.append(stock27)
    stock28 = Stock(count=321, id_book=28, id_shop=1)
    session_list.append(stock28)
    stock29 = Stock(count=987, id_book=29, id_shop=3)
    session_list.append(stock29)
    stock30 = Stock(count=856, id_book=30, id_shop=2)
    session_list.append(stock30)
    stock31 = Stock(count=9512, id_book=31, id_shop=3)
    session_list.append(stock31)
    stock32 = Stock(count=1587, id_book=32, id_shop=1)
    session_list.append(stock32)
    stock33 = Stock(count=1547, id_book=33, id_shop=2)
    session_list.append(stock33)
    stock34 = Stock(count=98741, id_book=34, id_shop=3)
    session_list.append(stock34)
    stock35 = Stock(count=1236, id_book=35, id_shop=1)
    session_list.append(stock35)
    stock36 = Stock(count=9870, id_book=36, id_shop=1)
    session_list.append(stock36)
    stock37 = Stock(count=987, id_book=37, id_shop=2)
    session_list.append(stock37)
    stock38 = Stock(count=158, id_book=38, id_shop=3)
    session_list.append(stock38)
    stock39 = Stock(count=3, id_book=39, id_shop=2)
    session_list.append(stock39)
    stock40 = Stock(count=87, id_book=40, id_shop=1)
    session_list.append(stock40)

    sale1 = Sale(price=345, date_sale='2022-07-28', id_stock=1, count=100)
    session_list.append(sale1)
    sale2 = Sale(price=123, date_sale='2022-08-26', id_stock=2, count=100)
    session_list.append(sale2)
    sale3 = Sale(price=435, date_sale='2022-09-30', id_stock=15, count=100)
    session_list.append(sale3)
    sale4 = Sale(price=432, date_sale='2022-10-26', id_stock=23, count=100)
    session_list.append(sale4)
    sale5 = Sale(price=355, date_sale='2022-11-15', id_stock=10, count=100)
    session_list.append(sale5)
    sale6 = Sale(price=127, date_sale='2022-12-31', id_stock=3, count=100)
    session_list.append(sale6)
    sale7 = Sale(price=128, date_sale='2023-01-19', id_stock=37, count=100)
    session_list.append(sale7)
    sale8 = Sale(price=234, date_sale='2023-02-23', id_stock=10, count=100)
    session_list.append(sale8)
    sale9 = Sale(price=125, date_sale='2022-03-26', id_stock=12, count=100)
    session_list.append(sale9)
    sale10 = Sale(price=109, date_sale='2022-04-09', id_stock=1, count=100)
    session_list.append(sale10)
    return session_list


session.add_all(insert_data())
session.commit()


for shop_name in session.query(Shop.shop_name). \
        join(Stock.shop). \
        join(Stock.book). \
        join(Book.publisher). \
        filter(Publisher.name == publisher) \
        .group_by(Shop.shop_name).all():
    print(shop_name[0])

session.close()
